# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      TEST_CMD: "test"
      CONDA_DEPENDENCIES: "cython scipy pandas"

  matrix:

      - PYTHON_VERSION: "2.7"
        NUMPY_VERSION: "stable"
        ASTROPY_VERSION: "stable"

      - PYTHON_VERSION: "3.5"
        NUMPY_VERSION: "stable"
        ASTROPY_VERSION: "stable"

platform:
    -x64

install:

    # Install Miniconda
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Test that PATH is set correctly
    - "conda --version"
    - "python --version"

    # Install pytest-fits
    - "pip install https://github.com/astrofrog/pytest-fits/archive/master.zip"

# Not a .NET project, we build ci-helpers in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py %TEST_CMD%"
